/*
 CREATE USER storesite IDENTIFIED BY 0000;
 GRANT ALL PRIVILEGES TO storesite;
 */


-- 슈퍼 관리자
CREATE TABLE SUPER_ADMIN (
   SUPER_ADMIN_ID VARCHAR2(50)  PRIMARY KEY, -- 슈퍼관리자 아이디
   SUPER_ADMIN_PW VARCHAR2(100) ,     -- 슈퍼관리자 패스워드
   AUTHORITY_ID   NUMBER(1)     NOT NULL  -- 권한ID
);

COMMENT ON TABLE SUPER_ADMIN IS '슈퍼 관리자';

COMMENT ON COLUMN SUPER_ADMIN.SUPER_ADMIN_ID IS '슈퍼관리자 아이디';
COMMENT ON COLUMN SUPER_ADMIN.SUPER_ADMIN_PW IS '슈퍼관리자 패스워드';
COMMENT ON COLUMN SUPER_ADMIN.AUTHORITY_ID IS '권한ID';

SELECT * FROM ALL_COL_COMMENTS WHERE TABLE_NAME = 'SUPER_ADMIN';



-- 권한
CREATE TABLE AUTHORITY (
   AUTHORITY_ID    NUMBER(1)    , -- 권한ID
   AUTHORITY_SCOPE VARCHAR2(50) ,  -- 권한범위
   PRIMARY KEY(AUTHORITY_ID, AUTHORITY_SCOPE)
);

COMMENT ON TABLE AUTHORITY IS '권한';

COMMENT ON COLUMN AUTHORITY.AUTHORITY_ID IS '권한ID';
COMMENT ON COLUMN AUTHORITY.AUTHORITY_SCOPE IS '권한범위';

SELECT * FROM ALL_COL_COMMENTS WHERE TABLE_NAME = 'AUTHORITY';


SELECT * FROM USER_TAB_COMMENTS;

-----------------------------------------------------

-- 슈퍼 관리자
SELECT * FROM SUPER_ADMIN;
-- 권한
SELECT * FROM AUTHORITY;

-----------------------------------------------------
-- 슈퍼 관리자
DROP TABLE SUPER_ADMIN;
-- 권한
DROP TABLE AUTHORITY;